language: node_js

node_js: 8

cache:
  yarn: true
  directories:
    - $HOME/.cache
    - public

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

jobs:
  include:
    - stage: warm cache
      script: true
    - stage: test
      script: yarn test --maxWorkers=2
    - stage: test
      node_js: 10
      script: yarn test --maxWorkers=2
    - stage: code coverage
      install: yarn add --dev coveralls
      script: yarn test --maxWorkers=2 --coverage --coverageReporters=text-lcov | coveralls

