// flow-typed signature: 6a815dabe6aab82b919c8f3da96dc523
// flow-typed version: <<STUB>>/eslint-config-wyze_v^4.1.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-wyze'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-wyze' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-wyze/base' {
  declare module.exports: any;
}

declare module 'eslint-config-wyze/flow' {
  declare module.exports: any;
}

declare module 'eslint-config-wyze/preact' {
  declare module.exports: any;
}

declare module 'eslint-config-wyze/rules/best-practices' {
  declare module.exports: any;
}

declare module 'eslint-config-wyze/rules/es6' {
  declare module.exports: any;
}

declare module 'eslint-config-wyze/rules/flow' {
  declare module.exports: any;
}

declare module 'eslint-config-wyze/rules/import' {
  declare module.exports: any;
}

declare module 'eslint-config-wyze/rules/legacy' {
  declare module.exports: any;
}

declare module 'eslint-config-wyze/rules/preact' {
  declare module.exports: any;
}

declare module 'eslint-config-wyze/rules/react' {
  declare module.exports: any;
}

declare module 'eslint-config-wyze/rules/style' {
  declare module.exports: any;
}

declare module 'eslint-config-wyze/rules/variables' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-wyze/base.js' {
  declare module.exports: $Exports<'eslint-config-wyze/base'>;
}
declare module 'eslint-config-wyze/flow.js' {
  declare module.exports: $Exports<'eslint-config-wyze/flow'>;
}
declare module 'eslint-config-wyze/index' {
  declare module.exports: $Exports<'eslint-config-wyze'>;
}
declare module 'eslint-config-wyze/index.js' {
  declare module.exports: $Exports<'eslint-config-wyze'>;
}
declare module 'eslint-config-wyze/preact.js' {
  declare module.exports: $Exports<'eslint-config-wyze/preact'>;
}
declare module 'eslint-config-wyze/rules/best-practices.js' {
  declare module.exports: $Exports<'eslint-config-wyze/rules/best-practices'>;
}
declare module 'eslint-config-wyze/rules/es6.js' {
  declare module.exports: $Exports<'eslint-config-wyze/rules/es6'>;
}
declare module 'eslint-config-wyze/rules/flow.js' {
  declare module.exports: $Exports<'eslint-config-wyze/rules/flow'>;
}
declare module 'eslint-config-wyze/rules/import.js' {
  declare module.exports: $Exports<'eslint-config-wyze/rules/import'>;
}
declare module 'eslint-config-wyze/rules/legacy.js' {
  declare module.exports: $Exports<'eslint-config-wyze/rules/legacy'>;
}
declare module 'eslint-config-wyze/rules/preact.js' {
  declare module.exports: $Exports<'eslint-config-wyze/rules/preact'>;
}
declare module 'eslint-config-wyze/rules/react.js' {
  declare module.exports: $Exports<'eslint-config-wyze/rules/react'>;
}
declare module 'eslint-config-wyze/rules/style.js' {
  declare module.exports: $Exports<'eslint-config-wyze/rules/style'>;
}
declare module 'eslint-config-wyze/rules/variables.js' {
  declare module.exports: $Exports<'eslint-config-wyze/rules/variables'>;
}
