// flow-typed signature: cf09b45a82bc18b469c96c17d96d71af
// flow-typed version: <<STUB>>/eslint-plugin-wyze_v^2.0.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-wyze'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-wyze' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-wyze/lib/rules/max-file-length' {
  declare module.exports: any;
}

declare module 'eslint-plugin-wyze/lib/rules/newline-after-export' {
  declare module.exports: any;
}

declare module 'eslint-plugin-wyze/lib/rules/sort-imports' {
  declare module.exports: any;
}

declare module 'eslint-plugin-wyze/lib/rules/space-around-conditional' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-wyze/index' {
  declare module.exports: $Exports<'eslint-plugin-wyze'>;
}
declare module 'eslint-plugin-wyze/index.js' {
  declare module.exports: $Exports<'eslint-plugin-wyze'>;
}
declare module 'eslint-plugin-wyze/lib/rules/max-file-length.js' {
  declare module.exports: $Exports<'eslint-plugin-wyze/lib/rules/max-file-length'>;
}
declare module 'eslint-plugin-wyze/lib/rules/newline-after-export.js' {
  declare module.exports: $Exports<'eslint-plugin-wyze/lib/rules/newline-after-export'>;
}
declare module 'eslint-plugin-wyze/lib/rules/sort-imports.js' {
  declare module.exports: $Exports<'eslint-plugin-wyze/lib/rules/sort-imports'>;
}
declare module 'eslint-plugin-wyze/lib/rules/space-around-conditional.js' {
  declare module.exports: $Exports<'eslint-plugin-wyze/lib/rules/space-around-conditional'>;
}
