// flow-typed signature: 46aca54ac6d1ca2c49ca688811fcd2f3
// flow-typed version: <<STUB>>/gh-got_v^5.0.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gh-got'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gh-got' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gh-got/index' {
  declare module.exports: $Exports<'gh-got'>;
}
declare module 'gh-got/index.js' {
  declare module.exports: $Exports<'gh-got'>;
}
