// flow-typed signature: d00b7ce8096eb13373c65765575c9698
// flow-typed version: <<STUB>>/koa-favicon_v^2.0.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-favicon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-favicon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'koa-favicon/index' {
  declare module.exports: $Exports<'koa-favicon'>;
}
declare module 'koa-favicon/index.js' {
  declare module.exports: $Exports<'koa-favicon'>;
}
