// flow-typed signature: 2cbf711d75a9ccc2e7c5d2d99ac7f241
// flow-typed version: <<STUB>>/piping_v^1.0.0-rc.4/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'piping'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'piping' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'piping/lib/piping' {
  declare module.exports: any;
}

declare module 'piping/src/piping' {
  declare module.exports: any;
}

declare module 'piping/test' {
  declare module.exports: any;
}

declare module 'piping/test/cleanup' {
  declare module.exports: any;
}

declare module 'piping/test/crash' {
  declare module.exports: any;
}

declare module 'piping/test/exit' {
  declare module.exports: any;
}

declare module 'piping/test/helpers/dummy' {
  declare module.exports: any;
}

declare module 'piping/test/helpers/index' {
  declare module.exports: any;
}

declare module 'piping/test/hook' {
  declare module.exports: any;
}

declare module 'piping/test/kill' {
  declare module.exports: any;
}

declare module 'piping/test/multiple' {
  declare module.exports: any;
}

declare module 'piping/test/request' {
  declare module.exports: any;
}

declare module 'piping/test/respawn' {
  declare module.exports: any;
}

// Filename aliases
declare module 'piping/lib/piping.js' {
  declare module.exports: $Exports<'piping/lib/piping'>;
}
declare module 'piping/src/piping.js' {
  declare module.exports: $Exports<'piping/src/piping'>;
}
declare module 'piping/test.js' {
  declare module.exports: $Exports<'piping/test'>;
}
declare module 'piping/test/cleanup.js' {
  declare module.exports: $Exports<'piping/test/cleanup'>;
}
declare module 'piping/test/crash.js' {
  declare module.exports: $Exports<'piping/test/crash'>;
}
declare module 'piping/test/exit.js' {
  declare module.exports: $Exports<'piping/test/exit'>;
}
declare module 'piping/test/helpers/dummy.js' {
  declare module.exports: $Exports<'piping/test/helpers/dummy'>;
}
declare module 'piping/test/helpers/index.js' {
  declare module.exports: $Exports<'piping/test/helpers/index'>;
}
declare module 'piping/test/hook.js' {
  declare module.exports: $Exports<'piping/test/hook'>;
}
declare module 'piping/test/kill.js' {
  declare module.exports: $Exports<'piping/test/kill'>;
}
declare module 'piping/test/multiple.js' {
  declare module.exports: $Exports<'piping/test/multiple'>;
}
declare module 'piping/test/request.js' {
  declare module.exports: $Exports<'piping/test/request'>;
}
declare module 'piping/test/respawn.js' {
  declare module.exports: $Exports<'piping/test/respawn'>;
}
