// flow-typed signature: cc01aa4a667985d8d5ca9e87f27e1962
// flow-typed version: <<STUB>>/snyk_v^1.25.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'snyk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'snyk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'snyk/cli/args' {
  declare module.exports: any;
}

declare module 'snyk/cli/commands/auth' {
  declare module.exports: any;
}

declare module 'snyk/cli/commands/config' {
  declare module.exports: any;
}

declare module 'snyk/cli/commands/help' {
  declare module.exports: any;
}

declare module 'snyk/cli/commands/index' {
  declare module.exports: any;
}

declare module 'snyk/cli/commands/modules' {
  declare module.exports: any;
}

declare module 'snyk/cli/commands/monitor' {
  declare module.exports: any;
}

declare module 'snyk/cli/commands/policy' {
  declare module.exports: any;
}

declare module 'snyk/cli/commands/protect/index' {
  declare module.exports: any;
}

declare module 'snyk/cli/commands/protect/prompts' {
  declare module.exports: any;
}

declare module 'snyk/cli/commands/protect/tasks' {
  declare module.exports: any;
}

declare module 'snyk/cli/commands/protect/wizard' {
  declare module.exports: any;
}

declare module 'snyk/cli/commands/scenario' {
  declare module.exports: any;
}

declare module 'snyk/cli/commands/test' {
  declare module.exports: any;
}

declare module 'snyk/cli/commands/unpublished/index' {
  declare module.exports: any;
}

declare module 'snyk/cli/commands/unpublished/prune' {
  declare module.exports: any;
}

declare module 'snyk/cli/commands/unpublished/walk' {
  declare module.exports: any;
}

declare module 'snyk/cli/commands/version' {
  declare module.exports: any;
}

declare module 'snyk/cli/copy' {
  declare module.exports: any;
}

declare module 'snyk/cli/index' {
  declare module.exports: any;
}

declare module 'snyk/dist/lodash-min' {
  declare module.exports: any;
}

declare module 'snyk/lib/analytics' {
  declare module.exports: any;
}

declare module 'snyk/lib/api-token' {
  declare module.exports: any;
}

declare module 'snyk/lib/bus' {
  declare module.exports: any;
}

declare module 'snyk/lib/capture' {
  declare module.exports: any;
}

declare module 'snyk/lib/config' {
  declare module.exports: any;
}

declare module 'snyk/lib/detect' {
  declare module.exports: any;
}

declare module 'snyk/lib/display-policy' {
  declare module.exports: any;
}

declare module 'snyk/lib/error' {
  declare module.exports: any;
}

declare module 'snyk/lib/exec' {
  declare module.exports: any;
}

declare module 'snyk/lib/hook' {
  declare module.exports: any;
}

declare module 'snyk/lib/hotload' {
  declare module.exports: any;
}

declare module 'snyk/lib/index' {
  declare module.exports: any;
}

declare module 'snyk/lib/is-ci' {
  declare module.exports: any;
}

declare module 'snyk/lib/isolate' {
  declare module.exports: any;
}

declare module 'snyk/lib/module-info/index' {
  declare module.exports: any;
}

declare module 'snyk/lib/module-info/maven/index' {
  declare module.exports: any;
}

declare module 'snyk/lib/module-info/maven/mvn-tree-parse' {
  declare module.exports: any;
}

declare module 'snyk/lib/module-info/npm/index' {
  declare module.exports: any;
}

declare module 'snyk/lib/module-info/rubygems/index' {
  declare module.exports: any;
}

declare module 'snyk/lib/module-info/rubygems/inspectors/gemfile' {
  declare module.exports: any;
}

declare module 'snyk/lib/module-info/rubygems/inspectors/gemspec' {
  declare module.exports: any;
}

declare module 'snyk/lib/module-info/rubygems/inspectors/index' {
  declare module.exports: any;
}

declare module 'snyk/lib/module-info/rubygems/inspectors/try-get-spec' {
  declare module.exports: any;
}

declare module 'snyk/lib/modules' {
  declare module.exports: any;
}

declare module 'snyk/lib/monitor' {
  declare module.exports: any;
}

declare module 'snyk/lib/npm' {
  declare module.exports: any;
}

declare module 'snyk/lib/protect/apply-patch' {
  declare module.exports: any;
}

declare module 'snyk/lib/protect/dedupe-patches' {
  declare module.exports: any;
}

declare module 'snyk/lib/protect/ensure-patch' {
  declare module.exports: any;
}

declare module 'snyk/lib/protect/fetch-patch' {
  declare module.exports: any;
}

declare module 'snyk/lib/protect/get-vuln-source' {
  declare module.exports: any;
}

declare module 'snyk/lib/protect/ignore' {
  declare module.exports: any;
}

declare module 'snyk/lib/protect/index' {
  declare module.exports: any;
}

declare module 'snyk/lib/protect/patch' {
  declare module.exports: any;
}

declare module 'snyk/lib/protect/patches-for-package' {
  declare module.exports: any;
}

declare module 'snyk/lib/protect/strip-versions' {
  declare module.exports: any;
}

declare module 'snyk/lib/protect/update' {
  declare module.exports: any;
}

declare module 'snyk/lib/protect/write-patch-flag' {
  declare module.exports: any;
}

declare module 'snyk/lib/request' {
  declare module.exports: any;
}

declare module 'snyk/lib/snyk-test/index' {
  declare module.exports: any;
}

declare module 'snyk/lib/snyk-test/maven/index' {
  declare module.exports: any;
}

declare module 'snyk/lib/snyk-test/npm/index' {
  declare module.exports: any;
}

declare module 'snyk/lib/snyk-test/rubygems/index' {
  declare module.exports: any;
}

declare module 'snyk/lib/spinner' {
  declare module.exports: any;
}

declare module 'snyk/lib/sub-process' {
  declare module.exports: any;
}

declare module 'snyk/lib/user-config' {
  declare module.exports: any;
}

declare module 'snyk/lib/version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'snyk/cli/args.js' {
  declare module.exports: $Exports<'snyk/cli/args'>;
}
declare module 'snyk/cli/commands/auth.js' {
  declare module.exports: $Exports<'snyk/cli/commands/auth'>;
}
declare module 'snyk/cli/commands/config.js' {
  declare module.exports: $Exports<'snyk/cli/commands/config'>;
}
declare module 'snyk/cli/commands/help.js' {
  declare module.exports: $Exports<'snyk/cli/commands/help'>;
}
declare module 'snyk/cli/commands/index.js' {
  declare module.exports: $Exports<'snyk/cli/commands/index'>;
}
declare module 'snyk/cli/commands/modules.js' {
  declare module.exports: $Exports<'snyk/cli/commands/modules'>;
}
declare module 'snyk/cli/commands/monitor.js' {
  declare module.exports: $Exports<'snyk/cli/commands/monitor'>;
}
declare module 'snyk/cli/commands/policy.js' {
  declare module.exports: $Exports<'snyk/cli/commands/policy'>;
}
declare module 'snyk/cli/commands/protect/index.js' {
  declare module.exports: $Exports<'snyk/cli/commands/protect/index'>;
}
declare module 'snyk/cli/commands/protect/prompts.js' {
  declare module.exports: $Exports<'snyk/cli/commands/protect/prompts'>;
}
declare module 'snyk/cli/commands/protect/tasks.js' {
  declare module.exports: $Exports<'snyk/cli/commands/protect/tasks'>;
}
declare module 'snyk/cli/commands/protect/wizard.js' {
  declare module.exports: $Exports<'snyk/cli/commands/protect/wizard'>;
}
declare module 'snyk/cli/commands/scenario.js' {
  declare module.exports: $Exports<'snyk/cli/commands/scenario'>;
}
declare module 'snyk/cli/commands/test.js' {
  declare module.exports: $Exports<'snyk/cli/commands/test'>;
}
declare module 'snyk/cli/commands/unpublished/index.js' {
  declare module.exports: $Exports<'snyk/cli/commands/unpublished/index'>;
}
declare module 'snyk/cli/commands/unpublished/prune.js' {
  declare module.exports: $Exports<'snyk/cli/commands/unpublished/prune'>;
}
declare module 'snyk/cli/commands/unpublished/walk.js' {
  declare module.exports: $Exports<'snyk/cli/commands/unpublished/walk'>;
}
declare module 'snyk/cli/commands/version.js' {
  declare module.exports: $Exports<'snyk/cli/commands/version'>;
}
declare module 'snyk/cli/copy.js' {
  declare module.exports: $Exports<'snyk/cli/copy'>;
}
declare module 'snyk/cli/index.js' {
  declare module.exports: $Exports<'snyk/cli/index'>;
}
declare module 'snyk/dist/lodash-min.js' {
  declare module.exports: $Exports<'snyk/dist/lodash-min'>;
}
declare module 'snyk/lib/analytics.js' {
  declare module.exports: $Exports<'snyk/lib/analytics'>;
}
declare module 'snyk/lib/api-token.js' {
  declare module.exports: $Exports<'snyk/lib/api-token'>;
}
declare module 'snyk/lib/bus.js' {
  declare module.exports: $Exports<'snyk/lib/bus'>;
}
declare module 'snyk/lib/capture.js' {
  declare module.exports: $Exports<'snyk/lib/capture'>;
}
declare module 'snyk/lib/config.js' {
  declare module.exports: $Exports<'snyk/lib/config'>;
}
declare module 'snyk/lib/detect.js' {
  declare module.exports: $Exports<'snyk/lib/detect'>;
}
declare module 'snyk/lib/display-policy.js' {
  declare module.exports: $Exports<'snyk/lib/display-policy'>;
}
declare module 'snyk/lib/error.js' {
  declare module.exports: $Exports<'snyk/lib/error'>;
}
declare module 'snyk/lib/exec.js' {
  declare module.exports: $Exports<'snyk/lib/exec'>;
}
declare module 'snyk/lib/hook.js' {
  declare module.exports: $Exports<'snyk/lib/hook'>;
}
declare module 'snyk/lib/hotload.js' {
  declare module.exports: $Exports<'snyk/lib/hotload'>;
}
declare module 'snyk/lib/index.js' {
  declare module.exports: $Exports<'snyk/lib/index'>;
}
declare module 'snyk/lib/is-ci.js' {
  declare module.exports: $Exports<'snyk/lib/is-ci'>;
}
declare module 'snyk/lib/isolate.js' {
  declare module.exports: $Exports<'snyk/lib/isolate'>;
}
declare module 'snyk/lib/module-info/index.js' {
  declare module.exports: $Exports<'snyk/lib/module-info/index'>;
}
declare module 'snyk/lib/module-info/maven/index.js' {
  declare module.exports: $Exports<'snyk/lib/module-info/maven/index'>;
}
declare module 'snyk/lib/module-info/maven/mvn-tree-parse.js' {
  declare module.exports: $Exports<'snyk/lib/module-info/maven/mvn-tree-parse'>;
}
declare module 'snyk/lib/module-info/npm/index.js' {
  declare module.exports: $Exports<'snyk/lib/module-info/npm/index'>;
}
declare module 'snyk/lib/module-info/rubygems/index.js' {
  declare module.exports: $Exports<'snyk/lib/module-info/rubygems/index'>;
}
declare module 'snyk/lib/module-info/rubygems/inspectors/gemfile.js' {
  declare module.exports: $Exports<'snyk/lib/module-info/rubygems/inspectors/gemfile'>;
}
declare module 'snyk/lib/module-info/rubygems/inspectors/gemspec.js' {
  declare module.exports: $Exports<'snyk/lib/module-info/rubygems/inspectors/gemspec'>;
}
declare module 'snyk/lib/module-info/rubygems/inspectors/index.js' {
  declare module.exports: $Exports<'snyk/lib/module-info/rubygems/inspectors/index'>;
}
declare module 'snyk/lib/module-info/rubygems/inspectors/try-get-spec.js' {
  declare module.exports: $Exports<'snyk/lib/module-info/rubygems/inspectors/try-get-spec'>;
}
declare module 'snyk/lib/modules.js' {
  declare module.exports: $Exports<'snyk/lib/modules'>;
}
declare module 'snyk/lib/monitor.js' {
  declare module.exports: $Exports<'snyk/lib/monitor'>;
}
declare module 'snyk/lib/npm.js' {
  declare module.exports: $Exports<'snyk/lib/npm'>;
}
declare module 'snyk/lib/protect/apply-patch.js' {
  declare module.exports: $Exports<'snyk/lib/protect/apply-patch'>;
}
declare module 'snyk/lib/protect/dedupe-patches.js' {
  declare module.exports: $Exports<'snyk/lib/protect/dedupe-patches'>;
}
declare module 'snyk/lib/protect/ensure-patch.js' {
  declare module.exports: $Exports<'snyk/lib/protect/ensure-patch'>;
}
declare module 'snyk/lib/protect/fetch-patch.js' {
  declare module.exports: $Exports<'snyk/lib/protect/fetch-patch'>;
}
declare module 'snyk/lib/protect/get-vuln-source.js' {
  declare module.exports: $Exports<'snyk/lib/protect/get-vuln-source'>;
}
declare module 'snyk/lib/protect/ignore.js' {
  declare module.exports: $Exports<'snyk/lib/protect/ignore'>;
}
declare module 'snyk/lib/protect/index.js' {
  declare module.exports: $Exports<'snyk/lib/protect/index'>;
}
declare module 'snyk/lib/protect/patch.js' {
  declare module.exports: $Exports<'snyk/lib/protect/patch'>;
}
declare module 'snyk/lib/protect/patches-for-package.js' {
  declare module.exports: $Exports<'snyk/lib/protect/patches-for-package'>;
}
declare module 'snyk/lib/protect/strip-versions.js' {
  declare module.exports: $Exports<'snyk/lib/protect/strip-versions'>;
}
declare module 'snyk/lib/protect/update.js' {
  declare module.exports: $Exports<'snyk/lib/protect/update'>;
}
declare module 'snyk/lib/protect/write-patch-flag.js' {
  declare module.exports: $Exports<'snyk/lib/protect/write-patch-flag'>;
}
declare module 'snyk/lib/request.js' {
  declare module.exports: $Exports<'snyk/lib/request'>;
}
declare module 'snyk/lib/snyk-test/index.js' {
  declare module.exports: $Exports<'snyk/lib/snyk-test/index'>;
}
declare module 'snyk/lib/snyk-test/maven/index.js' {
  declare module.exports: $Exports<'snyk/lib/snyk-test/maven/index'>;
}
declare module 'snyk/lib/snyk-test/npm/index.js' {
  declare module.exports: $Exports<'snyk/lib/snyk-test/npm/index'>;
}
declare module 'snyk/lib/snyk-test/rubygems/index.js' {
  declare module.exports: $Exports<'snyk/lib/snyk-test/rubygems/index'>;
}
declare module 'snyk/lib/spinner.js' {
  declare module.exports: $Exports<'snyk/lib/spinner'>;
}
declare module 'snyk/lib/sub-process.js' {
  declare module.exports: $Exports<'snyk/lib/sub-process'>;
}
declare module 'snyk/lib/user-config.js' {
  declare module.exports: $Exports<'snyk/lib/user-config'>;
}
declare module 'snyk/lib/version.js' {
  declare module.exports: $Exports<'snyk/lib/version'>;
}
