// flow-typed signature: be7fb2061eb4b2de3d9efcfeba6f1324
// flow-typed version: <<STUB>>/@wyze/koa-file-server_v^3.2.2/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@wyze/koa-file-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@wyze/koa-file-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@wyze/koa-file-server/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@wyze/koa-file-server/lib/index.js' {
  declare module.exports: $Exports<'@wyze/koa-file-server/lib/index'>;
}
