[package]
name = "index"
version = "1.0.0"
authors = [ "Neil Kistner <neil.kistner@gmail.com>" ]
edition = "2018"

[dependencies]
aes = "0.3"
base64 = "0.11"
block-modes = "0.3"
firestore-db-and-auth = "0.6"
hex = "0.4"
http = "0.1"
now_lambda = "*"
serde = "1.0"
