name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node v16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: yarn install --frozen-lockfile --check-files
    - run: yarn lint
    - run: GITHUB_ENDPOINT=${{ secrets.GH_ENDPOINT }} yarn build:codegen
    - run: yarn typecheck
    # - run: yarn test --coverage
    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v1
    #   with:
    #     fail_ci_if_error: true
    #     file: coverage/lcov.info
